name: ROS Timetable Check
on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
    types: [assigned, opened, synchronize, reopened]
jobs:
  ci-test:
    name: Test if Mergeable with Master Branch
    runs-on: ubuntu-latest
    container:
      image: artemisbeta/railwayopsim-ci:latest
      env:
        DEBIAN_FRONTEND : noninteractive
        LANG : 'en_GB.UTF-8' 
        LANGUAGE : 'en_GB:en' 
        LC_ALL : 'en_GB.UTF-8'
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Create branch for PR
        if: ${{ github.event_name == 'pull_request'}}
        run: git switch -c dev
      
      - name: Retrieve Master
        run: |
            git fetch origin master
            git checkout master
            git checkout ${{ steps.extract_branch.outputs.branch }}
        if: ${{ github.event_name != 'pull_request'}}

      - name: Retrieve Master
        run: |
          git fetch origin master
          git checkout master
          git checkout dev
        if: ${{ github.event_name == 'pull_request'}}

      - name: Run MR Merge Script
        run: git_merge_ttb ${{ steps.extract_branch.outputs.branch }} --soft --ttb-path Program_Timetables
        if: ${{ github.event_name != 'pull_request'}}

      - name: Run MR Merge Script
        run: git_merge_ttb dev --soft --ttb-path Program_Timetables
        if: ${{ github.event_name == 'pull_request'}}

      - uses: actions/upload-artifact@v1
        with:
          name: results
          path: 
            mr_check_output

      - uses: actions/download-artifact@v1
        with:
          name: results
        if: ${{ github.event_name == 'pull_request'}}
          
      - name: Comment Pull Request with Result
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: results/mr_check_output/mr-result.md
        if: ${{ github.event_name == 'pull_request'}}

      - name: Download Timetable Checker
        run: git clone https://github.com/Railway-Op-Sim/CI-Development.git
        
      - name: Check Contents
        run: ls CI-Development/software
        
      - uses: actions/upload-artifact@v1
        with:
            name: ttb_check
            path: |
                CI-Development/software/TimetableChecker.zip
                CI-Development/scripts/ttb_check.ps1

  run_timetable_check:
    needs: ci-test
    name: Run Timetable Checker
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Retrieve Timetable Checker
        uses: actions/download-artifact@v1
        with:
          name: ttb_check
      
      - name: Unpack Validator
        run: Expand-Archive -LiteralPath 'ttb_check\software\TimetableChecker.zip' -D 'TimetableChecker'
        shell: powershell

      - name: Prepare Files for Check
        run: |
            Copy-Item 'Program_Timetables\*.ttb' -destination '.'
            Copy-Item 'Railway\*.rly' -destination '.'
            Rename-Item -Path '*.ttb' -NewName 'temp.ttb'
            Rename-Item -Path '*.rly' -NewName 'railway.rly'
      
      - name: Run Timetable Checker on Test Files
        run: .\TimetableChecker\TimetableChecker\TimetableChecker.exe

      - name: Check Output
        run: .\ttb_check\scripts\ttb_check.ps1
        shell: powershell
